// Generated by CoffeeScript 1.3.3
(function() {

  define('openEpi', ['modules', 'angular', 'angular-twitter-bootstrap'], function(modules) {
    var getModule, onError, openEpi;
    openEpi = angular.module('openEpi', ['ui.bootstrap']);
    onError = function(message) {
      console.log('Error: ');
      return console.log(message);
    };
    getModule = function(moduleName) {
      var module;
      module = modules.getModule(moduleName);
      if (!(module != null)) {
        error("Could not find module named " + moduleName);
        return null;
      }
      return module;
    };
    openEpi.config([
      '$routeProvider', function($routeProvider) {
        $routeProvider.when('/', {
          templateUrl: 'partials/modules.html',
          controller: 'ModulesController'
        });
        $routeProvider.when('/module/:moduleName', {
          templateUrl: 'partials/module.html',
          controller: 'ModuleController'
        });
        return $routeProvider.otherwise({
          redirectTo: '/'
        });
      }
    ]);
    openEpi.controller('ModulesController', [
      '$rootScope', '$scope', '$location', function($rootScope, $scope, $location) {
        $scope.modules = modules;
        $scope.moduleLoad = function(moduleName) {
          return $location.path('/module/' + moduleName);
        };
        $scope.moduleFilter = function(module, filterTerm) {
          var tag, _i, _len, _ref;
          if (!(filterTerm != null)) {
            return true;
          }
          if (module.title.toLowerCase().indexOf(filterTerm.toLowerCase()) > -1) {
            return true;
          }
          _ref = module.tags;
          for (_i = 0, _len = _ref.length; _i < _len; _i++) {
            tag = _ref[_i];
            if (tag.toLowerCase().indexOf(filterTerm.toLowerCase()) > -1) {
              return true;
            }
          }
          return false;
        };
        return $scope.detailsTitle = function(detailsShown) {
          if (!detailsShown) {
            return "More Info";
          }
          return "Less Info";
        };
      }
    ]);
    openEpi.controller('ModuleController', [
      '$rootScope', '$scope', '$routeParams', '$location', function($rootScope, $scope, $routeParams, $location) {
        var module;
        module = getModule($routeParams.moduleName);
        module.resetInputModel();
        $scope.module = module;
        $scope.hasResult = false;
        $scope.result = {
          resultPaneActive: false
        };
        $scope.getDefaultValue = function(field) {
          if (field.defaultValue != null) {
            return field.defaultValue;
          }
          return '';
        };
        $scope.calculate = function() {
          return module.calculate(module.model, onError, function(result) {
            return module.renderData(result, function(data) {
              $scope.hasResult = true;
              $scope.result = data;
              return $scope.result.resultPaneActive = true;
            });
          });
        };
        return $scope.clear = function() {
          return module.resetInputModel();
        };
      }
    ]);
    angular.bootstrap(document, ['openEpi']);
    return openEpi;
  });

}).call(this);
